version: 2.1
description: Automatically build and push to your GitHub Repo Wiki

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Push Wiki To Project Wiki
          type: shell
          command: |
            git config user.email "${GITHUB_EMAIL}"
            git config user.name "${GITHUB_USERNAME}"
            git remote remove origin
            git remote add origin ${GITHUB_USERNAME}:${GITHUB_API_KEY}@git@github.com:rfearing/wiki-test.gitt > /dev/null 2>&1
            git remote add upstream ${GITHUB_USERNAME}:${GITHUB_API_KEY}@git@github.com:rfearing/wiki-test.git > /dev/null 2>&1
            git push origin HEAD:master > /dev/null 2>&1
            git push upstream HEAD:master > /dev/null 2>&1

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
